package_assets: off
compress_assets: off

javascripts:
    all:
        - public/javascripts/vendor/jquery.min.js
        #- public/javascripts/vendor/jquery-ui.min.js
        #- public/javascripts/vendor/jquery.fileupload.js
        #- public/javascripts/vendor/jquery.iframe-transport.js
        #- public/javascripts/vendor/jquery.fileupload-ui.js
        #- public/javascripts/vendor/mustache.js
        - public/javascripts/vendor/bootstrap.js
        #- public/javascripts/vendor/jquery.cycle.all.js
        - public/javascripts/components/c-front.js

stylesheets:
    all:
        - public/stylesheets/vendor/bootstrap.min.css
        - public/stylesheets/vendor/jquery-ui.css
        #- public/stylesheets/vendor/jquery-fileupload-ui.css
        - public/stylesheets/c-core.css
        - public/stylesheets/c-typography.css
        - public/stylesheets/c-home.css