default: &DEFAULT
  adapter: postgresql
  encoding: utf8
  min_messages: warning

  host: <%=ENV['db_host'] %>
  database: 'osconfny'
  username: <%=ENV['db_username']%>
  password: <%=ENV['db_password']%>

development:
  <<: *DEFAULT

production:
  <<: *DEFAULT

test:
  <<: *DEFAULT
